version: '3.9'
services:
  web:
    build: .
    ports:
        - "5000:5000"
    networks: 
        - "my_network"
    depends_on: 
        - db
  db:
    image: mysql:latest
    restart: always
    networks:
        my_network:
            aliases: 
                - my_database
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - my_db:/var/lib/mysql
volumes:
    my_db:

networks:
    my_network:
        driver: bridge