version: '3.5'
services:
  web:
    build: .
    ports:
        - "5000:5000"
    networks: 
        - "my_network"
    depends_on: 
        - db
  db:
    image: mysql:latest
    restart: always
    networks:
        my_network:
            aliases: 
                - my_database
    environment:
      MYSQL_DATABASE: 'db'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'user'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'password'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'rootpassword'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - my_db:/var/lib/mysql
# Names our volume
volumes:
    my_db:

networks:
    my_network:
        driver: bridge